# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3e5fbe52334e7f8986ef5ab612e502db15e125f3e68309a18262fc0cebe0ebdbe317dd6c4851298a374ec8580110cab3fcf40995e8f0aff8fab9bab66548fec

test:
  secret_key_base: a4cb4cef8f197b7d36447acbe47564e03263ea4dd8f8b5a85eeb573a17e415e37f143d2e9a44f6b18dcd77704a9fc3a516f211ef172e95422e2c137194b3af79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
